<?xml version="1.0" encoding="UTF-8"?><testrun name="MainTests" project="WebServer" tests="8" started="8" failures="1" errors="0" ignored="0">
  <testsuite name="com.vvs.webserver.unittest.webserver.MainTests" time="0.0">
    <testcase name="testMainInvalidNumber10" classname="com.vvs.webserver.unittest.webserver.MainTests" time="0.0"/>
    <testcase name="testMainInvalidBasePath" classname="com.vvs.webserver.unittest.webserver.MainTests" time="0.0"/>
    <testcase name="testMainInvalidNumber700000" classname="com.vvs.webserver.unittest.webserver.MainTests" time="0.0"/>
    <testcase name="testMainInvalidNumber" classname="com.vvs.webserver.unittest.webserver.MainTests" time="0.0"/>
    <testcase name="testMainValid" classname="com.vvs.webserver.unittest.webserver.MainTests" time="0.0">
      <failure>
        <expected>server was interrupted</expected>
        <actual>Usage: java Main port basePath maitenancePath
Error: port number must be between 1024 and 65535
</actual>org.junit.ComparisonFailure: expected:&lt;[server was interrupted]&gt; but was:&lt;[Usage: java Main port basePath maitenancePath
Error: port number must be between 1024 and 65535
]&gt;
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.vvs.webserver.unittest.webserver.MainTests.testMainValid(MainTests.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="testMainNull" classname="com.vvs.webserver.unittest.webserver.MainTests" time="0.0"/>
    <testcase name="testMainInvalidNumberOfParams0" classname="com.vvs.webserver.unittest.webserver.MainTests" time="0.0"/>
    <testcase name="testMainInvalidNumberOfParamsl" classname="com.vvs.webserver.unittest.webserver.MainTests" time="0.0"/>
  </testsuite>
</testrun>
